### ISSUE TITLE
$model->id

### ISSUE THREAD

**Issue by SpiritAbsolute** [CostaRico/yii2-images#30]
Hi!

I table the primary key is id_goods.
costa-rico/yii2-images/Module.php:82 here is an appeal to the $model->id
It gives an error message Getting unknown property: app\modules\admin\models\Products::id

sorry for bad english!

**Comment by CostaRico** [comment]
Hi, u should have "id" column in your table if you want to use this module. Also u could ask questions in Russian if it is more convenience. =)

**Comment by SpiritAbsolute** [comment]
Хорошо! :) А нельзя сделать совместимость в этом месте costa-rico/yii2-images/Module.php:82? Или сделать возможность создавать свою папку. Если мне не нужно каждому элементу создавать отдельную папку. Я хочу в общую папку сохранять все изображения. Сделать чтобы можно было задвать желаемый путь.

**Comment by CostaRico** [comment]
К каждому элементу будут создаваться разные копии изображения (большие, маленькие, превью и тд), поэтому необходима целая папка, иначе огромное кол-во файлов будет лежать в одной папке.
Модуль очень гибкий, ты можешь сделать форк от него. 
=)

**Comment by SpiritAbsolute** [comment]
Эх! Жаль нельзя прям из модели получать сразу PK а не ->id

**Comment by SpiritAbsolute** [comment]
А вот это не будет гавнокодом? :)
```
$id = array_shift($model::primaryKey());
$modelName = $this->getShortClass($model);
$modelDir = \yii\helpers\Inflector::pluralize($modelName).'/'. $modelName . $model->$id;
return $modelDir;
```

**Comment by CostaRico** [comment]
Зависит все от ситуации, а почему решили PK использовать не просто id?

**Comment by SpiritAbsolute** [comment]
Не уверен, не будет ли потом проблем из за этого и лишних слов при связывании таблиц. Захотел вот чтобы дублирования полей не было :)
