### ISSUE TITLE
Привет. Не могу разобраться как использовать yii2-images.

### ISSUE THREAD

**Issue by MatthewPattell** [CostaRico/yii2-images#31]
Установил, настроил модуль, миграцию применил, добавил бэхавиор. Что дальше?)
Добавил fileinput[], выбираю картинку(и), сохраняю(добавляю) и ничего(

**Comment by dub34** [comment]
Модуль так работает, что сначала ты должен картинку загрузить на сервер, а затем дернуть $model->attachImage(прямой путь к загруженной картинке);

**Comment by MatthewPattell** [comment]
Аааа, я думал все само работает) Т.е. я сам гружу картинку куда нужно и потом прикрепляю к модели? А превью нарезается как?

**Comment by dub34** [comment]
Так точно. Аттач принимает прямой путь к картинке в файловой системе.
превью нарезается так. 
$image = $model->getImage();
if($image){
    //get path to resized image 
    echo $image->getUrl('400x300');
}

Это в примерах есть.

**Comment by MatthewPattell** [comment]
В примерах есть, только допустим мне не совсем ясен принцип работы. Превью на лету что-ли режется/формируется?

**Comment by dub34** [comment]
первый раз да, затем подтягивает созданный файл

**Comment by MatthewPattell** [comment]
спасибо за разъяснения)
