### ISSUE TITLE
How remove not main image?

### ISSUE THREAD

**Issue by VoroninAndr** [CostaRico/yii2-images#38]
My model has a few images. How can I remove some of them? Not main.

**Comment by CostaRico** [comment]
> > //Returns main model image
> $image = $model->getImage();
> 
> if($image){
>     //get path to resized image 
>     echo $image->getPath('400x300');
> 
>     //path to original image
>     $image->getPathToOrigin();
> 
>     //will remove this image and all cache files
>     $model->removeImage($image);
> }

please, read docs.

**Comment by VoroninAndr** [comment]
I read docs. 
```
//Returns main model image
$image = $model->getImage();
```
this is return main image.
But my model, for example, has 10 images, how can I remove one of them, for example fifth?
I need something like 
`$model->removeImageByID($image_id);`

**Comment by CostaRico** [comment]
```
$img = Image::find($imageId);
$model->removeImage($img);
```
