### ISSUE TITLE
PHP Fatal Error Class 'abeautifulsite\SimpleImage' not found

### ISSUE THREAD

**Issue by nekit44** [CostaRico/yii2-images#57]
error
`Class 'abeautifulsite\SimpleImage' not found`
composer in the package have
tell me what to do?
`{
    "name": "yiisoft/yii2-app-basic",
    "description": "Yii 2 Basic Project Template",
    "keywords": ["yii2", "framework", "basic", "project template"],
    "homepage": "http://www.yiiframework.com/",
    "type": "project",
    "license": "BSD-3-Clause",
    "support": {
        "issues": "https://github.com/yiisoft/yii2/issues?state=open",
        "forum": "http://www.yiiframework.com/forum/",
        "wiki": "http://www.yiiframework.com/wiki/",
        "irc": "irc://irc.freenode.net/yii",
        "source": "https://github.com/yiisoft/yii2"
    },
    "minimum-stability": "stable",
    "require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": "~2.0.5",
        "yiisoft/yii2-bootstrap": "~2.0.0",
        "yiisoft/yii2-swiftmailer": "~2.0.0",
        "costa-rico/yii2-images": "^1.0",
        "abeautifulsite/simpleimage": "^3.2"
    },
    "require-dev": {
        "yiisoft/yii2-debug": "~2.0.0",
        "yiisoft/yii2-gii": "~2.0.0",
        "yiisoft/yii2-faker": "~2.0.0",

        "codeception/base": "^2.2.3",
        "codeception/verify": "~0.3.1",
        "codeception/specify": "~0.4.3"
    },
    "config": {
        "process-timeout": 1800
    },
    "scripts": {
        "post-create-project-cmd": [
            "yii\\composer\\Installer::postCreateProject"
        ]
    },
    "extra": {
        "yii\\composer\\Installer::postCreateProject": {
            "setPermission": [
                {
                    "runtime": "0777",
                    "web/assets": "0777",
                    "yii": "0755"
                }
            ],
            "generateCookieValidationKey": [
                "config/web.php"
            ]
        },
        "asset-installer-paths": {
            "npm-asset-library": "vendor/npm",
            "bower-asset-library": "vendor/bower"
        }
    }
}
`

**Comment by uniqby** [comment]
+1 have same error.

Temporary fix: 
add to composer.json
```
"abeautifulsite/simpleimage": "2.7",
```
then composer update

**Comment by gaginsgagins** [comment]
+1 have same error.

**Comment by CostaRico** [comment]
@uniqby thx, just made a commit

**Comment by VictorZZZZ** [comment]
> Temporary fix:
> add to composer.json
> 
> "abeautifulsite/simpleimage": "2.7",

Helped me too. Thank's
