### ISSUE TITLE
Class 'abeautifulsite\SimpleImage' not found

### ISSUE THREAD

**Issue by AleksandrGol** [CostaRico/yii2-images#58]
Hi!
Can't understand why.

```
$image = $data->getImage();
return "<img src='{$image->getUrl()}'>";
```

but
`$image->getPathToOrigin();
`shows full path correctly.
Please, help!

**Comment by CostaRico** [comment]
$image->getPathToOrigin() should return path to original file
$data->getImage() should return Image object

what is the question exactly?

**Comment by AleksandrGol** [comment]
If
`$image = $data->getImage();
return "<img src='{$image->getUrl()}'>";`
I get Class 'abeautifulsite\SimpleImage' not found (500 internal server error)

**Comment by CostaRico** [comment]
ok, got it
it seems something changed in SImpleImage repo

https://github.com/CostaRico/yii2-images/issues/57


Please, I made a new release, pls, reinstall the package with composer and feedback me, thx a lot.

**Comment by AleksandrGol** [comment]
Yeah, it works! Thank you!
