### ISSUE TITLE
Error for save the model where in tables primary key not ID

### ISSUE THREAD

**Issue by AlienMans** [CostaRico/yii2-images#62]
Для таблиц в базе данных для которых модели созданы с первичным ключом отличным от ID метод getModelSubDir не может вернуть правильное значение.

Решение проблемы в файле Module,php строка 82

$modelDir = \yii\helpers\Inflector::pluralize($modelName).'/'. $modelName . $model->getTableSchema()->primaryKey;

**Comment by AlienMans** [comment]
Точнее проблема решена так:
$tbl_primaryKey = $model->getTableSchema()->primaryKey[0];
$modelDir = \yii\helpers\Inflector::pluralize($modelName).'/'. $modelName . $model->$tbl_primaryKey;

**Comment by CostaRico** [comment]
Добрый день, если сделаете пулл реквест – проакцептю.

**Comment by mailamir** [comment]
Достаточно добавить

public function getId()
    {
        return $this::findOne(['user_id' => $this->user_id])->user_id;
    }
