### ISSUE TITLE
Ошибка после обновления replace "id" with getPrimaryKey()

### ISSUE THREAD

**Issue by svetlana-k** [CostaRico/yii2-images#70]
Ошибка после обновления http://joxi.ru/12MP4yH4WnB9mJ
Calling unknown method: rico\yii2images\Module::getPrimaryKey()

**Comment by CostaRico** [comment]
@svetlana-k получилось справиться?

**Comment by alex290** [comment]
Картинки теперь вообще не показывают. Пришлось откатить на старую версию

**Comment by svetlana-k** [comment]
теперь все ок.

**Comment by CostaRico** [comment]
@alex290 не могли бы вы подробнее описать проблему?

**Comment by alex290** [comment]
Я написал в новый [пост](https://github.com/CostaRico/yii2-images/issues/72)

**Comment by Inkognitoo** [comment]
@CostaRico когда выкатите обновление? Не очень удобно каждый раз лезть в папку vendor для исправления

**Comment by Ivanitch** [comment]
Херовое расширение. Сделал глупость однажды-установил его, теперь костылить приходится. Решил проблему (незнаю, правда насколько это правильно), добавив в urlManager
-------------------------------------------------------------------------------------------
'<id:([0-9])+>/images/image-by-item-and-alias' => 'yii2images/images/image-by-item-and-alias',
